server:
  port: 8090
spring:
  data:
    mongodb:
      database: userdb
      host: mongodb
      port: 27017

admin:
  username: admin
  password: admin
  jwt_secret: jwtSecret
  jwt_token_validity_period: 864000000
public_client:
  client_id: ui_client
  client_secret: ui_secret
  access_token_validity_period: 3600
  refresh_token_validity_period: 86400




