spring:
  data:
    mongodb:
      database: userdb
      host: mongodb
      port: 27017
  thymeleaf:
    cache: false

admin:
  client_id: admin_client
  client_secret: admin

public_client:
  client_id: ui_client
  access_token_validity_period: 3600
  refresh_token_validity_period: 86400




