version: "3"
services:
  mongodb:
    image: mongo:bionic
    container_name: "mongodb"
    ports:
      - 27017:27017
  auth-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8090:8090
    links:
      - mongodb