version: "3"
services:
  mongodb:
    image: mongo:bionic
    container_name: "mongodb"
    ports:
      - 27017:27017
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    links:
      - mongodb