version: "3"
services:
  mongodb:
    image: mongo:bionic
    container_name: "mongodb"
    ports:
      - 27017:27017
  auth-server:
    build:
      context: ../server
      dockerfile: docker/Dockerfile
    ports:
      - 8090:8090
    links:
      - mongodb
  auth-ui:
    build:
      context: ../ui
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    links:
      - auth-server
