version: "3"
services:
  mongodb:
    image: mongo:bionic
    container_name: "mongodb"
    ports:
      - 27017
  auth-server:
    image: docker.pkg.github.com/opencarrentalproject/authorization-service/authorization-service:latest
    container_name: auth-server
    ports:
      - 8090:8090
    links:
      - mongodb
  auth-ui:
    image: docker.pkg.github.com/opencarrentalproject/authorization-service/authorization-ui:latest
    container_name: auth-ui
    ports:
      - 80:80
    links:
      - auth-server
